---
  - name: Create frontend zone
    ansible.posix.firewalld:
      zone: "frontend"
      state: present
      permanent: true
    register: create_frontend

  - name: Open frontend ports
    ansible.posix.firewalld:
      port: "{{ item }}/tcp"
      zone: frontend
      state: enabled
      permanent: true
    register: open_frontend_ports
    with_items: "{{ firewall_frontend_open_ports }}"

  - name: Create backend zone
    ansible.posix.firewalld:
      zone: "backend"
      state: present
      permanent: true
    register: create_backend

  - name: Open backend ports
    ansible.posix.firewalld:
      port: "{{ item }}/tcp"
      zone: backend
      state: enabled
      permanent: true
    register: open_backend_ports
    with_items: "{{ firewall_backend_open_ports }}"

  # We need to reload the firewall before adding the interface to frontend
  - name: reload firewall
    command: firewall-cmd --reload
    when: create_frontend.changed or open_frontend_ports.changed or create_backend.changed or open_backend_ports.changed

  - name: Check frontend interfaces
    command: firewall-cmd --zone=frontend --list-interfaces
    check_mode: false
    changed_when: false
    register: frontend_interfaces

  - name: Add network interfaces to frontend
    command: firewall-cmd --permanent --zone=frontend --change-interface={{ item }}
    when: item not in frontend_interfaces.stdout
    with_items: "{{  haproxy_frontend_network_interfaces  }}"

  - name: Check backend interfaces
    command: firewall-cmd --zone=backend --list-interfaces
    check_mode: false
    changed_when: false
    register: backend_interfaces

  - name: Add network interfaces to frontend
    command: firewall-cmd --permanent --zone=backend --change-interface={{ item }}
    when: item not in backend_interfaces.stdout
    with_items: "{{  haproxy_backend_network_interfaces  }}"
